---
title: "Weed Veez"
output:
  html_document:
    toc: TRUE
    code_folding : "hide"
    number_sections : TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, fig.align="center", error=FALSE)
```


```{r libraries, message=FALSE,eval=TRUE}

library(ggplot2)
library(dplyr)
library(hrbrthemes)
library(viridis)
library(plotly)
library(tidyverse)
```

This is a test `r aer`.

***



```{r lollipop, message=FALSE,eval=TRUE}
###### Lollipop chart : Mean by state, HighQ, MedQ and LowQ
Mean_HighQ_state = data.frame(aggregate(HighQ~State, data=df, FUN=function(df) c(mean=mean(df), count=length(df))))
Mean_HighQ_state$HighQ = Mean_HighQ_state$HighQ[1:51]
attach(Mean_HighQ_state)
# Mean_MedQ_state = aggregate(MedQ~State, data=df, FUN=function(df) c(mean=mean(df), count=length(df)))
# Mean_LowQ_state = aggregate(LowQ~State, data=df, FUN=function(df) c(mean=mean(df), count=length(df)))

geom_point( size=5, color="red", fill=alpha("orange", 0.3), alpha=0.7, shape=21, stroke=2) 

# Reorder
Mean_HighQ_state %>%
  arrange(HighQ) %>%
  mutate(State=factor(State,State)) %>%
  ggplot(aes(x=State, y=HighQ)) +
    geom_segment( aes(x=State, xend=State, y=0, yend=HighQ), color="skyblue") +
    geom_point( size=3, color="red", fill=alpha("orange", 0.3), alpha=0.7, shape=21, stroke=2) +
    theme_light() +
    coord_flip() +
    theme(
      panel.grid.major.y = element_blank(),
      panel.border = element_blank(),
      axis.ticks.y = element_blank()
    ) +
    xlab("") +
    ylab("Mean price per state") +
    
    annotate("text", x=State[HighQ==max(HighQ)], y=max(HighQ) - 160,
      label=("North Dakota : 415$/oz. (28g)"), color="red") +
    annotate(geom="point", State[HighQ==max(HighQ)], y=max(HighQ), shape=21, size=10, fill="transparent", color="red") +
    
    annotate("text", x=State[HighQ==min(HighQ)], y=min(HighQ) - 100,
      label=("Oregon : 208$/oz."), color="red") +
    annotate(geom="point", State[HighQ==min(HighQ)], y=min(HighQ), shape=21, size=10, fill="transparent", color="red") +
    
    geom_hline(yintercept=mean(HighQ), color="blue", size=.5) +
    annotate("text", x=State[HighQ==min(HighQ)], y=min(HighQ) + 100,
           label=("Mean : 330$/oz."), color="blue")
```

<!-- {r, fig.cap="Figure: Here is a really important caption."} -->

